local set = vim.opt

set.backup = false
set.writebackup = false
set.encoding = 'utf-8'
set.tabstop = 4
set.softtabstop = 4
set.shiftwidth = 4
set.expandtab = true
set.splitbelow = true
set.splitright = true
set.relativenumber = true
set.number = true
set.autoindent = true
set.smartindent = true
set.wrap = false
set.laststatus = 2
set.showtabline = 2
set.incsearch = true
set.guifont = 'Hack'
set.background = 'dark'
set.termguicolors = true
set.updatetime = 100
